### ISSUE TITLE
arg (licenses) does not name a directory, bucket, or bucket subdir

### ISSUE THREAD

**Issue by huanvu** [GoogleCloudPlatform/cloud-builders-community#105]
Having some issues with the copy-licenses step which later on gives me this issue

```
Step #1: Step 16/18 : COPY licenses licenses
Step #1: COPY failed: stat /var/lib/docker/tmp/docker-builder155253068/licenses: no such file or directory
```

I've tried both using the env var and the gs bucket. Am I missing something? Thank you.

**Comment by etet-etet** [comment]
I guess you should make "licenses" directory in your local project. It worked fine in my case.

**Comment by sanastos** [comment]
I'm not sure what this is referring to, please reopen if this is still an issue.
