### ISSUE TITLE
Android Builder Should Use Gradle Wrapper

### ISSUE THREAD

**Issue by ccjernigan** [GoogleCloudPlatform/cloud-builders-community#117]
In the Android [gradle-build](https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/android/gradle-build) script, the script is using `gradle` when the best practice is to use the gradle wrapper `gradlew`.

The version of gradle being installed by the [Dockerfile](https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/android/Dockerfile) is version 4.4 which won't work with the latest version of the Android Gradle plugin.  Using `gradlew` avoids the need to keep updating the Dockerfile.

Caching should still be fine, as the gradle download ends up in the directory that is already being cached.

**Comment by spierre99** [comment]
I have the same problem. WOuld it be possible to have a fix on this ?

**Comment by dlackty** [comment]
This is a good idea that I didn't think of while working on #122. I'll give it a try this week.

**Comment by rharter** [comment]
This has been resolved either the new Android cloud builder. I'd recommend closing this issue and reopening it if this crops up again.
