### ISSUE TITLE
Android Builder Overwrites Artifacts

### ISSUE THREAD

**Issue by ccjernigan** [GoogleCloudPlatform/cloud-builders-community#118]
In the Android [simple-cloudbuild.yaml](https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/android/android-build-example/simple-cloudbuild.yaml), the example writes the the output to a fixed path based on project, branch, and git commit.  If a build is run more than once on the same commit, the build outputs will be overwritten.

By adding the $BUILD_ID to the output path, the artifacts from previous invocations of the same build would be preserved.

**Comment by rharter** [comment]
This has been resolved either the new Android cloud builder. I'd recommend closing this issue and reopening it if this crops up again.
