### ISSUE TITLE
Terraform builds from sub dirs

### ISSUE THREAD

**Issue by kurtmaile** [GoogleCloudPlatform/cloud-builders-community#155]
Hi,

I am exploring using cloudbuild for building out terraform infra but was wanting to ask for help what appears to be a simple request.

My .tf files are in sub directories within the checkout source code from github - in order to do a terraform init, I need to 'cd' (docker WORKDIR) to a sub directory before executing a specific terraform command.

Is there a basic cloudbuild 'step' for this Im missing to do this before executing an actual terraform command?  Im not a docker expert (far from it!) so any help for a newbie appreciated.

Thanks!

**Comment by kurtmaile** [comment]
figured out there is a 'dir' field you can provide as per the doco!

**Comment by nof20** [comment]
:)
