### ISSUE TITLE
firebase - vulnerabilities in official npm builder

### ISSUE THREAD

**Issue by Masahigo** [GoogleCloudPlatform/cloud-builders-community#172]
Hi,

I was creating a custom build step based on the [firebase builder](https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/firebase) and also testing _Container Analysis API_ and it detected several vulnerabilities in this image which were caused by the [official npm builder](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/npm)

![image](https://user-images.githubusercontent.com/9364649/51744036-3a39bb00-20a7-11e9-9b44-662a1498c5af.png)

Once I changed the base image in the custom build step's Dockerfile to use latest Node LTS (Boron) the vulnerabilities were gone.

FROM gcr.io/cloud-builders/npm
-->
FROM node:boron

BR
Masi

**Comment by nof20** [comment]
Hi Masi.  I took a quick look at the Dockerfile and cloudbuild.yaml and I think this is just a timing issue.  Vuln Scans can take a little while to complete - I bet if you go back and look again you'll see a very similar amount to the original version.

The official [Dockerhub node images](https://hub.docker.com/_/node/) are available for a variety of distros, so if you're concerned about reducing your vulnerability surface I'd recommend looking at Alpine (i.e. `FROM node:lts-alpine ...`).  Note also LTS is now dubnium not boron.

Hope that helps.
