### ISSUE TITLE
Limit to one concurrent build per branch/tag per repo.

### ISSUE THREAD

**Issue by istack-robel** [GoogleCloudPlatform/cloud-builders-community#198]
Hi,

Been looking for resources regarding limiting concurrent build execution per branch/tag/repo at a time but found none. Is this currently supported or is there any workaround to achieve this?

Thank you!

**Comment by nof20** [comment]
Hi there.  Nothing available like this at the moment that I know of.

I can imagine a way to do it - your first build step could poll the Cloud Build API, get a list of all builds in progress, and fail if one is already in progress.  I would expect the [build source](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds#source) would have the info you're looking for, although you'd have to check it does exactly what you want for your setup.
