### ISSUE TITLE
kustomize:latest not found

### ISSUE THREAD

**Issue by Kampe** [GoogleCloudPlatform/cloud-builders-community#226]
## Affected builder image

(e.g., `gcr.io/cloud-builders-community/helm`)

## Expected Behavior
The image pulls down and is available for use on Cloud Build

## Actual Behavior
When trying to use this image, using both gcr.io/cloud-builders/kustomize as well as gcr.io/<My Project>/kustomize (which is stated to use in the docs) results in no available images for Kustomize. 

## Steps to Reproduce the Problem

1. Use either gcr.io/cloud-builders/kustomize
2. or gcr.io/<My Project>/kustomize as a image for cloudbuild to utilize
3.

## Additional Info
Were the images pulled?  There's none available?

**Comment by nof20** [comment]
Hi there, you need to build your own kustomize image using the source in this repository.  Clone `cloud-builders-community`, go to the kustomize directory, run `gcloud builds submit . --config=cloudbuild.yaml`, and then afterwards you can use `gcr.io/$PROJECT_ID/kustomize` in your builds.  But you have to build it first.  Hope that helps.

**Comment by Kampe** [comment]
Thanks! Kinda figured that after I thought about it some more heh - this looks great thanks!
