### ISSUE TITLE
Android SDK not found error

### ISSUE THREAD

**Issue by Soorya-S** [GoogleCloudPlatform/cloud-builders-community#241]
I'm getting an error while running the cloud build.
Here's the log

Step #2 - "build": BUILD FAILED in 1m 38s
Step #2 - "build": 
Step #2 - "build": * Get more help at https://help.gradle.org
Step #2 - "build": 
Step #2 - "build": Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Step #2 - "build": * Try:
Step #2 - "build": 
Step #2 - "build": > The SDK directory '/workspace/C:\Users\91880\AppData\Local\Android\Sdk' does not exist.
Step #2 - "build": A problem occurred configuring project ':app'.
Step #2 - "build": * What went wrong:
Step #2 - "build": 
Step #2 - "build": FAILURE: Build failed with an exception.
Step #2 - "build": 
Step #2 - "build": Daemon will be stopped at the end of the build stopping after processing
Step #2 - "build": To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.1.1/userguide/gradle_daemon.html.
Step #2 - "build": 
Step #2 - "build": For more details see https://docs.gradle.org/5.1.1/release-notes.html
Step #2 - "build": 
Step #2 - "build":  - Production-ready configuration avoidance APIs
Step #2 - "build":  - Control which dependencies can be retrieved from which repositories
Step #2 - "build": Here are the highlights of this release:
Step #2 - "build": 
Step #2 - "build": Welcome to Gradle 5.1.1!

How to fix this?

**Comment by nof20** [comment]
Hi there.  Your config somewhere includes "C:\Users\91880\...", which is not a valid path on Linux.  (Cloud Build uses Linux.)

Try using a relative directory instead.

**Comment by Soorya-S** [comment]
Hey!
Thanks for the response. 
I've fixed it now.
