### ISSUE TITLE
`docker-compose` fails on `run` argument.

### ISSUE THREAD

**Issue by mans0954** [GoogleCloudPlatform/cloud-builders-community#242]
## Affected builder image

`docker-compose`

## Expected Behavior

docker-compose/README.md states "Arguments passed to this builder will be passed to docker-compose directly, allowing callers to run any docker-compose command."

I would therefore expect running
```
gcloud  builds submit --config=cloudbuild.yaml .
```
on a modified `examples/hello-world/cloudbuild.yaml`:
```
steps:
- name: 'gcr.io/cloud-builders-community/docker-compose'
  args: ['run','helloworld']
```
to output
```
Step #0: Hello world
```

## Actual Behavior

Running
```
gcloud  builds submit --config=cloudbuild.yaml .
```
on the modified `examples/hello-world/cloudbuild.yaml`:
```
steps:
- name: 'gcr.io/cloud-builders-community/docker-compose'
  args: ['run','helloworld']
```
outputs
```
Couldn't find `docker` binary. You might need to install Docker:

https://docs.docker.com/engine/installation/
ERROR
ERROR: build step 0 "gcr.io/overleaf-ops/docker-compose" failed: exit status 1
--------------------------------------------------------------------------------------------------------------------------------

ERROR: (gcloud.builds.submit) build 086991cb-c5f0-47d7-80b1-fd5e39fe4f49 completed with status "FAILURE"
```

## Steps to Reproduce the Problem

Change directory to `docker-compose/examples/hello-world`. Edit the `cloudbuild.yaml` file:
```
steps:
- name: 'gcr.io/cloud-builders-community/docker-compose'
  args: ['run','helloworld']
```
Run
```
gcloud  builds submit --config=cloudbuild.yaml .
```

## Additional Info

The problem can be solved by adding the `docker-ce-cli` package to the `docker-compose` image.

**Comment by boothead** [comment]
I just updated to the latest version and had the same problem
