### ISSUE TITLE
Cloud Builders Flutter not working

### ISSUE THREAD

**Issue by johnlina** [GoogleCloudPlatform/cloud-builders-community#258]
## Affected builder image

https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/flutter
gcr.io/cloud-builders/flutter

## Expected Behavior

The build process was done with success.

## Actual Behavior

Step #1: Error response from daemon: Get https://gcr.io/v2/cloud-builder/flutter/manifests/latest: denied: Token exchange failed for project 'cloud-builder'. Please enable or contact project owners to enable the Google Container Registry API in Cloud Console at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?project=cloud-builder before performing this operation.
Step #1: Using default tag: latest

## Steps to Reproduce the Problem

1. Create the cloudbuild.yaml with the following configuration:

steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/flutter/flutter']
    dir: '/workspace'

  - name: 'gcr.io/cloud-builder/flutter'
    entrypoint: '/bin/bash'
    args: ['build.sh']

**Comment by sanastos** [comment]
Is 'cloud-builder' your project? You should be building the flutter builder in your own project and then running it from your own project (and the container registry API should be enabled for your project).

Take a look at the examples folder for the flutter builder.

If this is still a problem please reopen the issue.
