### ISSUE TITLE
Please consider Cloud Building these images in gcr.io/cloud-builders-community repo

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/cloud-builders-community#262]
## Affected builder image

All

## Expected Behavior
IIUC there is no build automation for this repo nor is there a GCR repo that hosts the results.
```bash
docker pull gcr.io/cloud-builders-community/protoc
```

## Actual Behavior
```bash
git clone git@github.com:GoogleCloudPlatform/cloud-builders-community.git
cd cloud-builders-community
cd protoc
gcloud builds submit ...
docker pull gcr.io/${PROJECT}/protoc
```
Wasted energy cloning, building, storing images when they could be accessed similarly to the Google-sanctioned `gcr.io/cloud-builders`.

These images are hosted on `github.com/GoogleCloudPlatform`. I think it would be sufficient to push these to a distinct repo to make it clear these are community-provided.

**Comment by ImJasonH** [comment]
We'd love to! Unfortunately outside constraints prevent this from being feasible. ☹️
