### ISSUE TITLE
Sonarqube with Google Cloud build not working

### ISSUE THREAD

**Issue by ankitsoni5** [GoogleCloudPlatform/cloud-builders-community#269]
I am trying to run sonarqube analysis while automatic docker images building process using Google cloud build on my repo.

I have followed the steps give in : https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/sonarqube

But when I commit the code on github my trigger fails. Below is my cloudbuild.yaml file and error.
> cloudbuild.yaml
steps:
   
- name: 'gcr.io/PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=server-ip'
    - '-Dsonar.login=c2a7631a6e402c338739091ffbc30e5e3d66cf19'
    - '-Dsonar.projectKey=sample-project'
    - '-Dsonar.sources=.'
 
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/PROJECT_ID/html-css-website-course', '.' ]

images:
- 'gcr.io/concrete-crow-244606/html-css-website-course'

> error in build history of Cloud Build:

Status: Build failed
Status detail: failed unmarshalling build config cloudbuild.yaml: yaml: line 3: did not find expected key

I have "gcr.io/concrete-crow-244606/sonar-scanner:latest" image pushed in gcloud container registry.
My sonarqube server running on a GCP instance and is working fine.

**Comment by harshmanvar** [comment]
@ankitsoni5  It's indentation error please try this 

```
- name: gcr.io/$PROJECT_ID/sonar-scanner:latest
  args:
    - '-Dsonar.host.url=<value>'
    - '-Dsonar.login=<value>'
    - '-Dsonar.projectKey=<value>'
    - '-Dsonar.sources=.'
```
For me this is working but i am getting error in sonar-scanner image that we have to build and upload to GCR.

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/launch.sh\": permission denied": unknown.
Finished Step #1`

**Comment by ankitsoni5** [comment]
Thanks @harshmanvar 
The issue already got resolved. :)

**Comment by harshmanvar** [comment]
@ankitsoni5 can you please help me i am getting this error after uploading image to GCR.

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/launch.sh\": permission denied": unknown. Finished Step #1`

**Comment by nicholausadi** [comment]
> @ankitsoni5 It's indentation error please try this
> 
> ```
> - name: gcr.io/$PROJECT_ID/sonar-scanner:latest
>   args:
>     - '-Dsonar.host.url=<value>'
>     - '-Dsonar.login=<value>'
>     - '-Dsonar.projectKey=<value>'
>     - '-Dsonar.sources=.'
> ```
> 
> For me this is working but i am getting error in sonar-scanner image that we have to build and upload to GCR.
> 
> `docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/launch.sh\": permission denied": unknown. Finished Step #1`

I also got the same error. Can someone help me?

**Comment by harsh4870** [comment]
This config working for me : https://github.com/harsh4870/sonarqube-kubernetes/blob/master/deployment.yaml

**Comment by nicholausadi** [comment]
@harsh4870 That is config for sonarqube deployment.

I'm using sonarcloud.io and want to add sonar-scanner in cloudbuild, but I got this error in cloudbuild log.
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/launch.sh\": permission denied": unknown. Finished Step #1`
