### ISSUE TITLE
I want to use image in asia.gcr.io, but always call to gcr.io

### ISSUE THREAD

**Issue by ALTELMA** [GoogleCloudPlatform/cloud-builders-community#292]
## Affected builder image
(e.g., `asia.gcr.io/cloud-builders-community/slackbot`)

## Expected Behavior
I build an image in asia.gcr.io

## Actual Behavior
When building successfully it tries to find an image in gcr.io always.

Please suggest me how to fix this?

**Comment by sanastos** [comment]
Please reopen this with a reproducible example (a link to a repo is sufficient).

Before doing so, make sure that you both _built_ and _referenced_ the image in asia.gcr.io; most builders build in the default region and use the default region for examples.
