### ISSUE TITLE
Support Hugo Extended

### ISSUE THREAD

**Issue by Fleker** [GoogleCloudPlatform/cloud-builders-community#310]
## Affected builder image

(e.g., `gcr.io/cloud-builders-community/hugo`)

## Expected Behavior
I expected to be able to use SCSS and SASS in my Hugo project without issue

## Actual Behavior
I run into an error documented on the [developer site](https://gohugo.io/troubleshooting/faq/#i-get-this-feature-is-not-available-in-your-current-hugo-version). It seems like the default Hugo builder pulls in 0.57.2 where it should pull in 0.57.2_extended.

## Steps to Reproduce the Problem
1. Deploy default Hugo GCR
2. Clone a doc theme like [docsy](https://github.com/google/docsy)
3. Have a simple Hugo project. The Docsy sample project could work.
4. In your `cloudbuild.yaml`, add the step

```yaml
- name: gcr.io/$PROJECT_ID/hugo
  dir: docs
  args: []
  id: Generate HTML
```

**Comment by Fleker** [comment]
Interestingly, I can't seem to simply change the [Dockerfile](https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/hugo/Dockerfile) to be `_extended` as it spits out a shared object error:

```
Step #1: Already have image: gcr.io/$PROJECT_ID/hugo
Step #1: /hugo: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/$PROJECT_ID/hugo" failed: exit status 127
```

**Comment by esteluk** [comment]
Given the MR above was merged in as-is, this issue could probably be closed unless there's a desire to include images for both the extended and not extended versions.
