### ISSUE TITLE
rocker builder is broken

### ISSUE THREAD

**Issue by Philmod** [GoogleCloudPlatform/cloud-builders-community#38]
```
Starting Step #2
Step #2: Already have image: gcr.io/community-builders/rocker
Step #2: rocker version built locally - none (none) none
Finished Step #2
Starting Step #3
Step #3: Already have image: gcr.io/community-builders/rocker
Step #3: INFO[0000] FROM gcr.io/cloud-builders/docker 
Step #3: INFO[0000] | Image sha256:15ada size=463.1 MB
Step #3: INFO[0000] COPY ./bin/rocker /usr/bin/rocker 
Step #3: INFO[0000] | Calculating tarsum for 1 files (14.58 MB total) 
Step #3: FATA[0000] archive/tar: missed writing 4120 bytes 
Finished Step #3
ERROR
ERROR: build step 3 "gcr.io/community-builders/rocker" failed: exit status 1
```

**Comment by bendory** [comment]
Broken due to https://github.com/grammarly/rocker/issues/196

**Comment by bendory** [comment]
Workaround until then: https://github.com/GoogleCloudPlatform/cloud-builders-community/commit/11e371e6f091e8c3f6600d77df16feb7a00ba1ec

**Comment by Thomas-Roper** [comment]
It looks like grammarly is [no longer supporting the open source rocker project](https://github.com/grammarly/rocker/blob/master/README.md). I don't think the root cause is going to be addressed.

**Comment by bendory** [comment]
https://github.com/GoogleCloudPlatform/cloud-builders-community/commit/4fe0938c4b7e618b69f482aa5afbd0389761d4f3
