### ISSUE TITLE
@grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0 while running build in the CloudBuild

### ISSUE THREAD

**Issue by alisherk** [GoogleCloudPlatform/cloud-builders-community#413]
## Affected builder image
gcr.io/cloud-builders-community/firebase`
(e.g., `gcr.io/cloud-builders-community/helm`)

## Expected Behavior
While running unit tests with the image, I am getting this error @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0. I expect these tests to pass as they do in my local env. 
## Actual Behavior
Step #4:       5 | import 'firebase/functions';
Step #4:       4 | import 'firebase/storage';
Step #4:       3 | import 'firebase/auth';
Step #4:         | ^
Step #4:     > 2 | import 'firebase/firestore';
Step #4:       1 | import firebase from 'firebase/app';
Step #4: 
Step #4:     @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0

## Steps to Reproduce the Problem
Once CloudBuild is set up and linked to my github repo to trigger on changes to the master branch, this happens. 
## Additional Info
This worked fine a few weeks ago. I am not sure if if this is bug with firebase-tools or perhaps the Node version needs to be updated in the image. I updated the Node to version 10 in the dockerfile but it does not seem to have helped.

**Comment by Nisthar** [comment]
any updates? i am getting same issue on my electron.

**Comment by alisherk** [comment]
@Nisthar  solution is you will have to define a higher version of Node in your cloudbuild.yaml file like so 
`# Run tests on the front end
- name: node:10.16.0
  entrypoint: npm 
  args: ['run', 'test:unit']

**Comment by alisherk** [comment]
I will close this issue
