### ISSUE TITLE
Sonarscanner image failed to run error daemon: OCI runtime "exec: \"/launch.sh\": permission denied": unknown

### ISSUE THREAD

**Issue by nicholausadi** [GoogleCloudPlatform/cloud-builders-community#439]
## Affected builder image

(e.g., `gcr.io/cloud-builders-community/sonarqube`)

## Expected Behavior
Cloud build log show this log
`START: Running sonar-scanner-cli on date`

## Actual Behavior
Cloud build log show this error log
```shell
ERROR
ERROR: build step 3 "gcr.io/project-test-1104/sonar-scanner:latest" failed: starting step container failed: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/launch.sh\": permission denied": unknown
```

## Steps to Reproduce the Problem

1. Clone sonarqube
2. Build and upload to Cloud Registry
3. Run cloud build with this step
```shell
- name: gcr.io/my-project/sonar-scanner:latest
  args: 
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login=<value>'
    - '-Dsonar.projectKey=<value>'
    - '-Dsonar.organization=<value>'
    - '-Dsonar.sources=./packages'
```

**Comment by nicholausadi** [comment]
The issue got resolved.

For anyone who experience the same problem: 
My advice **don't use windows** for submit build to GCR. I think there is a problem in docker windows.
Please use Linux or Mac OS run this command `gcloud builds submit --config cloudbuild.yaml .` like the documentation say https://github.com/GoogleCloudPlatform/cloud-builders-community#build-the-build-step-from-source

Refence issue #423

**Comment by sindunuragarp** [comment]
For anyone who faces this issue again, the cause is due to `launch.sh` missing execution permission. The solution is to grant the file execution permissions before deploying it to gcloud.

```
> chmod +x launch.sh
> gcloud builds submit --config cloudbuild.yaml .
```
