### ISSUE TITLE
Feature request: add link to nice instructions on google cloud for firebase builder

### ISSUE THREAD

**Issue by Robbie-Cook** [GoogleCloudPlatform/cloud-builders-community#452]
## Feature Request Description

I have noticed that the instructions for the firebase builder come from https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-firebase, but there is no reference back to these docs in the README. 

I proposed adding a link to https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-firebase in the firebase builder README. This will mean:

* Users will have those nice blue buttons to enable all the APIs at once
* Users will have access to nicely displayed, simpler, and formatted instructions

**Comment by akauppi** [comment]
@Robbie-Cook Making a PR would likely make this happen?

**Comment by Robbie-Cook** [comment]
Yip! It's already merged! https://github.com/GoogleCloudPlatform/cloud-builders-community/pull/453
