### ISSUE TITLE
Getting GCE error when trying to use the windows builder

### ISSUE THREAD

**Issue by nishant-shah-social** [GoogleCloudPlatform/cloud-builders-community#537]
## Affected builder image
gcr.io/cloud-builders-community/windows-builder

## Expected Behavior
Should be able to use the windows-builder image successfully in google cloud build

## Actual Behavior
Getting the below error message specific to GCE :-
`Starting GCE service in project playground-nishant
2021/10/12 06:35:00 GCE Instances insert call failed: googleapi: Error 400: Invalid value for field 'resource.tags.items[0]': ''. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid`
## Steps to Reproduce the Problem

1. Simply followed the steps mentioned here :- https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/windows-builder

## Additional Info
I performed these steps from a mac book. Hope it should not be a problem

**Comment by isarkis** [comment]
@perezd, is the --tags option mandatory? If so, we'll need to update the README.md.

**Comment by perezd** [comment]
I didn't intend to make it required, does it appear to be? If so we can make it optional.

**Comment by isarkis** [comment]
Yes, windows-builder throws an error without --tags argument.

**Comment by perezd** [comment]
OK, that's a mistake. Send a PR to make it optional?

**Comment by isarkis** [comment]
PTAL https://github.com/GoogleCloudPlatform/cloud-builders-community/pull/544

**Comment by isarkis** [comment]
Can someone help close this issue, it's been fixed?
