### ISSUE TITLE
cloudbuild-ndk.yaml using NDK that hasn't been supported since 2018

### ISSUE THREAD

**Issue by DanAlbert** [GoogleCloudPlatform/cloud-builders-community#576]
## Affected builder image

https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/android/cloudbuild-ndk.yaml

## Expected Behavior

Uses a supported NDK

## Actual Behavior

r17 wasn't even supported at the time this file was added

## Steps to Reproduce the Problem

1. Look at the file
2. See that it's using r17
3. Compare to the list of supported releases on https://github.com/android/ndk/wiki

## Additional Info

I haven't sent a PR updating the file because I'm not sure if the issue is the file choosing old images, or if there are no newer images to select.

**Comment by khuey** [comment]
I will send a PR for this at some point.
