### ISSUE TITLE
Helm version bump

### ISSUE THREAD

**Issue by kvokka** [GoogleCloudPlatform/cloud-builders-community#606]
The repo is using Helm 3.7.0, which is way behind the current Helm 3.11.0

I don't mind adding a PR for it, but I saw such beginnings in the past with the lack of approval/merge.

In light of the https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke using this image would be required more often.

**Comment by wyardley** [comment]
@kvokka I came across this after throwing up #618 
I had this and some other changes locally

But yeah, not sure who can actually review this, and this project doesn't seem super actively maintained. I'll see if someone in the GCP Slack can get someone to take a look.

**Comment by wyardley** [comment]
#619 would also fully drop v2 / tiller support
