### ISSUE TITLE
Provide community gcr.io repo

### ISSUE THREAD

**Issue by wstrange** [GoogleCloudPlatform/cloud-builders-community#77]
It would be really nice to not have to build these images, but just reference using something like:
gcr.io/cloud-builders-community/

Understood that they come with no warranty....

**Comment by nof20** [comment]
Hey @wstrange.  Thanks for the idea: we understand this would make it a lot easier to get started with these tools.  We explored the possibility but unfortunately we can't host the images for legal reasons.
