### ISSUE TITLE
firebase - permission error

### ISSUE THREAD

**Issue by mnimer** [GoogleCloudPlatform/cloud-builders-community#78]
I'm trying to run the firebase cloud-builder however I get this error when it tries to run the step. 

Step #1: docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/firebase.bash\": permission denied": unknown.

Any ideas or workarounds? 

thanks,
--mike

**Comment by akohen** [comment]
I'm getting the same error here :(

**Comment by akohen** [comment]
I think the fix is to run `sudo chmod +x firebase.bash` before building the container... Made a PR with this.

**Comment by boon1515** [comment]
I'm still  getting same error with using current master version, anything I miss out?

**Comment by evheath** [comment]
I am also getting this error running only a simple 'firebase list' and nothing else

**Comment by nof20** [comment]
That's now fixed - please `git pull` and rebuild.  Sorry for the inconvenience.
