### ISSUE TITLE
Question about docker compose build

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [GoogleCloudPlatform/cloud-builders-community#90]
If docker-compose build step is used to create and detach a composed YAML how do I access the containers in next step. E.g. I create a "webserver" container and expose port 80 of the container -> localhost. However in the next "ubuntu" build step I cannot access this container e.g. both localhost:8000 and webserver:80 don't work. 

The NPM integration test example makes it seem as if the containers created from previous compose step should be accessible next steps. But since each step runs in a "container" do I need to explicitly forward the host/port ?

**Comment by mbana** [comment]
Wondering the same thing.

**Comment by wstewartii** [comment]
I'd also like to know the answer to this.

**Comment by wstewartii** [comment]
I was able to resolve by adding an external network key to my docker-compose.yaml like in this [example](https://github.com/Philmod/gcb-docker-compose/blob/master/docker-compose.yml#L21-L24). I created a separate docker-compose file with `version: "2"` at the top of the file followed by the networking bit and I run them both in container builder with ```docker-compose -f docker-compose.yaml -f <path to networking file> up```

**Comment by AKSHAYUBHAT** [comment]
Just verified that it works!
