### ISSUE TITLE
Defind Variable in fabric-beta-dist-cloudbuild.yaml

### ISSUE THREAD

**Issue by ramzyhassan44** [GoogleCloudPlatform/cloud-builders-community#98]
I am trying to use fabric-beta-dist-cloudbuild.yaml  in android cloud builder for beta distribution but I can't figured out the value of the variables in your yaml filel like 

- ${_SIGNING_BUCKET_PATH}
- ${_FABRIC_API_SECRET_BUCKET_PATH}
- ${_EMAIL_DISTRIBUTION_GROUP}
- _BUILD_TYPE_CAPITALIZED

**Comment by rharter** [comment]
Using the Fabric Gradle plugin these arguments aren't required.

I'd recommend closing this issue and reopening it if this crops up again.
